### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by rectangle-man** [IEEE-VIT/RazorType#6]
Design a results page, name it "Results.jsx" in the src folder.
The results page shall contain:
1) Navigation Bar
2) A counter for the speed of the user
3) A counter for the accuracy of the user
4) A counter displaying the total words typed, the number of incorrect words typed along with the total time taken to type the assignment.

**Comment by praveenraj-rs** [comment]
hi @rectangle-man and @KaviyaKumarr 
I am interested to work on this topic. 
so, can you assign it.
